In [1]:
import pandas as pd

In [2]:
s = pd.Series([12, 34, 423, 412, 123, 125, 23, 656, 232])

In [3]:
s

0     12
1     34
2    423
3    412
4    123
5    125
6     23
7    656
8    232
dtype: int64

In [5]:
s.values

array([ 12,  34, 423, 412, 123, 125,  23, 656, 232], dtype=int64)

In [6]:
s.index

RangeIndex(start=0, stop=9, step=1)

In [7]:
dates = pd.date_range('20190401', periods=9)
s.index = dates
s

2019-04-01     12
2019-04-02     34
2019-04-03    423
2019-04-04    412
2019-04-05    123
2019-04-06    125
2019-04-07     23
2019-04-08    656
2019-04-09    232
Freq: D, dtype: int64

In [8]:
s.index

DatetimeIndex(['2019-04-01', '2019-04-02', '2019-04-03', '2019-04-04',
               '2019-04-05', '2019-04-06', '2019-04-07', '2019-04-08',
               '2019-04-09'],
              dtype='datetime64[ns]', freq='D')

In [9]:
s.name='test'

In [10]:
s

2019-04-01     12
2019-04-02     34
2019-04-03    423
2019-04-04    412
2019-04-05    123
2019-04-06    125
2019-04-07     23
2019-04-08    656
2019-04-09    232
Freq: D, Name: test, dtype: int64

In [12]:
import numpy as np
s['2019-04-10'] = np.nan

In [13]:
s

2019-04-01 00:00:00     12.0
2019-04-02 00:00:00     34.0
2019-04-03 00:00:00    423.0
2019-04-04 00:00:00    412.0
2019-04-05 00:00:00    123.0
2019-04-06 00:00:00    125.0
2019-04-07 00:00:00     23.0
2019-04-08 00:00:00    656.0
2019-04-09 00:00:00    232.0
2019-04-10               NaN
Name: test, dtype: float64

In [14]:
len(s)

10

In [15]:
s.shape

(10,)

In [16]:
s.count()

9

In [17]:
s.unique()

array([ 12.,  34., 423., 412., 123., 125.,  23., 656., 232.,  nan])

In [18]:
s.value_counts()

232.0    1
656.0    1
23.0     1
125.0    1
123.0    1
412.0    1
423.0    1
34.0     1
12.0     1
Name: test, dtype: int64

In [19]:
data_dict = { 'BABA': 187.07, 'PDD': 21.83, 'JD': 30.79, 'BIDU': 184.77 }
s3 = pd.Series(data_dict)

In [20]:
s3

BABA    187.07
BIDU    184.77
JD       30.79
PDD      21.83
dtype: float64

In [22]:
s3.index.name = 'stock_code'
s3

stock_code
BABA    187.07
BIDU    184.77
JD       30.79
PDD      21.83
dtype: float64

In [23]:
df1 = pd.DataFrame( np.array([[1, 2, 3], [4, 5, 6]]) )
df1

0  1  2
0  1  2  3
1  4  5  6

In [24]:
symbol = ['BABA', 'JD', 'AAPL', 'MS', 'GS', 'WMT']
data = {'行业': ['电商', '电商', '科技', '金融', '金融', '零售'],
        '价格': [176.92, 25.95, 172.97, 41.79, 196.00, 99.55],
        '交易量': [16175610, 27113291, 18913154, 10132145, 2626634, 8086946],
        '雇员': [101550, 175336, 100000, 60348, 36600, 2200000]}
df2 = pd.DataFrame(data, index=symbol)
df2.name = '美股'
df2.index.name = '代号'
df2

交易量      价格  行业       雇员
代号                                 
BABA  16175610  176.92  电商   101550
JD    27113291   25.95  电商   175336
AAPL  18913154  172.97  科技   100000
MS    10132145   41.79  金融    60348
GS     2626634  196.00  金融    36600
WMT    8086946   99.55  零售  2200000

In [25]:
df2.values

array([[16175610, 176.92, '电商', 101550],
       [27113291, 25.95, '电商', 175336],
       [18913154, 172.97, '科技', 100000],
       [10132145, 41.79, '金融', 60348],
       [2626634, 196.0, '金融', 36600],
       [8086946, 99.55, '零售', 2200000]], dtype=object)

In [27]:
df2.index

Index(['BABA', 'JD', 'AAPL', 'MS', 'GS', 'WMT'], dtype='object', name='代号')

In [28]:
df2.columns

Index(['交易量', '价格', '行业', '雇员'], dtype='object')

In [29]:
df2.describe()

交易量          价格            雇员
count  6.000000e+00    6.000000  6.000000e+00
mean   1.384130e+07  118.863333  4.456390e+05
std    8.717312e+06   73.748714  8.607522e+05
min    2.626634e+06   25.950000  3.660000e+04
25%    8.598246e+06   56.230000  7.026100e+04
50%    1.315388e+07  136.260000  1.007750e+05
75%    1.822877e+07  175.932500  1.568895e+05
max    2.711329e+07  196.000000  2.200000e+06

In [30]:

df2.index = pd.MultiIndex.from_tuples( 
            [('中国公司','BABA'), ('中国公司','JD'), 
             ('美国公司','AAPL'), ('美国公司','MS'), 
             ('美国公司','GS'), ('美国公司','WMT')] )
df2

交易量      价格  行业       雇员
中国公司 BABA  16175610  176.92  电商   101550
     JD    27113291   25.95  电商   175336
美国公司 AAPL  18913154  172.97  科技   100000
     MS    10132145   41.79  金融    60348
     GS     2626634  196.00  金融    36600
     WMT    8086946   99.55  零售  2200000

In [31]:
df = df2

In [33]:
df.loc[df.雇员 >= 100000]

交易量      价格  行业       雇员
中国公司 BABA  16175610  176.92  电商   101550
     JD    27113291   25.95  电商   175336
美国公司 AAPL  18913154  172.97  科技   100000
     WMT    8086946   99.55  零售  2200000