In [1]:
import numpy as np

In [2]:
train_x = []
train_y = []
with open('./测试数据/数据分类/朴素贝叶斯/train.txt') as f_train:
    for line in f_train.readlines():
        train_x_y_tmp = line.split('\t')[-1]
#         print(train_x_y_tmp)
        train_y_tmp, train_x_tmp = train_x_y_tmp.split(':')
        train_x_tmp = train_x_tmp.strip().split(',')
#         print(train_x_tmp)
        train_x.append(train_x_tmp)
        train_y.append(train_y_tmp)
        
train_x = np.array(train_x, dtype='float32')
train_y = np.array(train_y, dtype='int')
print(train_x)
print(train_y)

[[ 92. 115. 120. ... 107. 113.  87.]
 [ 84. 102. 106. ...  99. 104.  79.]
 [ 84. 102. 102. ...  99. 104.  79.]
 ...
 [ 68.  75. 108. ... 100. 104.  85.]
 [ 71.  87. 108. ...  91. 104.  85.]
 [ 71.  91. 100. ...  91. 100.  81.]]
[3 3 3 ... 4 4 4]


In [3]:
classes = np.unique(train_y)

In [4]:
classes

array([1, 2, 3, 4, 5, 6])

In [5]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(train_x, train_y, random_state=0)

In [6]:
# 支持向量机
from sklearn.svm import SVC

In [ ]:
clf = SVC(kernel='linear', C=1E6).fit(Xtrain, ytrain)

In [ ]:
from sklearn.metrics import accuracy_score
y_predict = clf.predict(Xtest)
accuracy_score(ytest, y_predict)